export const NODE_TYPES_CONFIG = {
  threatActor: {
    label: 'Threat Actor',
    letter: 'A',
    color: 'bg-red-600',
    border: 'border-red-400',
    text: 'text-red-100',
    badge: 'bg-red-800',
    icon: '🎭',
    description: 'Who — adversary, insider, nation-state',
    defaultData: { title: 'Threat Actor', description: '', actorType: '', motivation: '' },
  },
  attackVector: {
    label: 'Attack Vector',
    letter: 'V',
    color: 'bg-orange-500',
    border: 'border-orange-300',
    text: 'text-orange-100',
    badge: 'bg-orange-700',
    icon: '⚡',
    description: 'How — phishing, SQLi, MITM, supply chain',
    defaultData: { title: 'Attack Vector', description: '', technique: '', reference: '' },
  },
  attackSurface: {
    label: 'Attack Surface',
    letter: 'S',
    color: 'bg-yellow-500',
    border: 'border-yellow-300',
    text: 'text-yellow-900',
    badge: 'bg-yellow-700',
    icon: '🎯',
    description: 'What — asset, API, service, database',
    defaultData: { title: 'Attack Surface', description: '', assetType: '', owner: '' },
  },
  control: {
    label: 'Control',
    letter: 'C',
    color: 'bg-blue-600',
    border: 'border-blue-400',
    text: 'text-blue-100',
    badge: 'bg-blue-800',
    icon: '🛡️',
    description: 'Security control — existing, weak, or missing',
    defaultData: { title: 'Control', description: '', status: 'missing', controlType: '' },
  },
  impact: {
    label: 'Impact',
    letter: 'I',
    color: 'bg-purple-600',
    border: 'border-purple-400',
    text: 'text-purple-100',
    badge: 'bg-purple-800',
    icon: '💥',
    description: 'What happens if the threat is realized',
    defaultData: { title: 'Impact', description: '', impactType: '', severity: '' },
  },
  threat: {
    label: 'Threat',
    letter: 'T',
    color: 'bg-gray-800',
    border: 'border-gray-500',
    text: 'text-gray-100',
    badge: 'bg-gray-900',
    icon: '☠️',
    description: 'Composite VICAR threat with ranking',
    defaultData: { title: 'Threat', description: '', ranking: 'medium', notes: '' },
  },
  trustBoundary: {
    label: 'Trust Boundary',
    letter: 'Z',
    color: 'bg-gray-800',
    border: 'border-dashed border-gray-500',
    text: 'text-gray-200',
    badge: 'bg-gray-900',
    icon: '🔒',
    description: 'Zone — DMZ, Internal, Cloud...',
    isZone: true,
    defaultData: { title: '', zoneType: 'internal' },
  },
};

export const RANKING_CONFIG = {
  low: { label: 'Low', color: 'bg-green-500', text: 'text-white' },
  medium: { label: 'Medium', color: 'bg-yellow-400', text: 'text-gray-900' },
  high: { label: 'High', color: 'bg-red-500', text: 'text-white' },
};

// Zone types for Trust Boundary nodes (inline styles to avoid Tailwind purging)
export const ZONE_STYLES = {
  external:   { border: '#ef4444', bg: 'rgba(127,29,29,0.15)',   text: '#f87171', label: 'External / Internet' },
  dmz:        { border: '#eab308', bg: 'rgba(113,63,18,0.15)',   text: '#facc15', label: 'DMZ' },
  internal:   { border: '#22c55e', bg: 'rgba(20,83,45,0.15)',    text: '#4ade80', label: 'Internal Network' },
  cloud:      { border: '#3b82f6', bg: 'rgba(30,58,138,0.15)',   text: '#60a5fa', label: 'Cloud Infrastructure' },
  thirdparty: { border: '#a855f7', bg: 'rgba(88,28,135,0.15)',   text: '#c084fc', label: 'Third Party' },
};

export const CONTROL_STATUS_CONFIG = {
  existing: { label: '✅ Existing', color: 'text-green-400' },
  weak: { label: '⚠️ Weak', color: 'text-yellow-400' },
  missing: { label: '❌ Missing', color: 'text-red-400' },
};
