export const NODE_TYPES_CONFIG = {
  threatActor: {
    label: 'Threat Actor',
    letter: 'A',
    color: 'bg-red-600',
    border: 'border-red-400',
    text: 'text-red-100',
    badge: 'bg-red-800',
    icon: '🎭',
    description: 'Who — adversary, insider, nation-state',
    defaultData: { title: 'Threat Actor', description: '', actorType: '', motivation: '' },
  },
  attackVector: {
    label: 'Attack Vector',
    letter: 'V',
    color: 'bg-orange-500',
    border: 'border-orange-300',
    text: 'text-orange-100',
    badge: 'bg-orange-700',
    icon: '⚡',
    description: 'How — phishing, SQLi, MITM, supply chain',
    defaultData: { title: 'Attack Vector', description: '', technique: '', reference: '' },
  },
  attackSurface: {
    label: 'Attack Surface',
    letter: 'S',
    color: 'bg-yellow-500',
    border: 'border-yellow-300',
    text: 'text-yellow-900',
    badge: 'bg-yellow-700',
    icon: '🎯',
    description: 'What — asset, API, service, database',
    defaultData: { title: 'Attack Surface', description: '', assetType: '', owner: '' },
  },
  control: {
    label: 'Control',
    letter: 'C',
    color: 'bg-blue-600',
    border: 'border-blue-400',
    text: 'text-blue-100',
    badge: 'bg-blue-800',
    icon: '🛡️',
    description: 'Security control — existing, weak, or missing',
    defaultData: { title: 'Control', description: '', status: 'missing', controlType: '' },
  },
  impact: {
    label: 'Impact',
    letter: 'I',
    color: 'bg-purple-600',
    border: 'border-purple-400',
    text: 'text-purple-100',
    badge: 'bg-purple-800',
    icon: '💥',
    description: 'What happens if the threat is realized',
    defaultData: { title: 'Impact', description: '', impactType: '', severity: '' },
  },
  threat: {
    label: 'Threat',
    letter: 'T',
    color: 'bg-gray-800',
    border: 'border-gray-500',
    text: 'text-gray-100',
    badge: 'bg-gray-900',
    icon: '☠️',
    description: 'Composite VICAR threat with ranking',
    defaultData: { title: 'Threat', description: '', ranking: 'medium', notes: '' },
  },
};

export const RANKING_CONFIG = {
  low: { label: 'Low', color: 'bg-green-500', text: 'text-white' },
  medium: { label: 'Medium', color: 'bg-yellow-400', text: 'text-gray-900' },
  high: { label: 'High', color: 'bg-red-500', text: 'text-white' },
};

export const CONTROL_STATUS_CONFIG = {
  existing: { label: '✅ Existing', color: 'text-green-400' },
  weak: { label: '⚠️ Weak', color: 'text-yellow-400' },
  missing: { label: '❌ Missing', color: 'text-red-400' },
};

// Auto-suggested edge labels based on source → target node type pairs
export const RELATIONSHIP_LABELS = {
  'threatActor->attackVector':  'uses',
  'threatActor->attackSurface': 'targets',
  'threatActor->threat':        'performs',
  'attackVector->attackSurface':'exploits',
  'attackVector->control':      'bypasses',
  'attackVector->impact':       'leads to',
  'attackVector->threat':       'constitutes',
  'attackSurface->impact':      'leads to',
  'attackSurface->control':     'protected by',
  'control->attackVector':      'mitigates',
  'control->threat':            'reduces',
  'control->attackSurface':     'secures',
  'impact->threat':             'ranks',
  'threat->impact':             'causes',
  'threat->control':            'remediated by',
  default:                      'relates to',
};
